### ISSUE TITLE
Can paths be made relative?

### ISSUE THREAD

**Issue by ianhandel** [CharlotteWoolley/growth_cleanR#7]
Currently paths to evaluate R scripts are absolute.

E.g.
'/Users/s1576473/dev/growth_cleanR/data_prep_and_error_simulation/simulate_errors_CLOSER_data.R'

They'd be clearer and simpler if relative to project/code root directory.

E.g.
'data_prep_and_error_simulation/simulate_errors_CLOSER_data.R'

**Comment by CharlotteWoolley** [comment]
Had some problems with setting this up initially because I was working within function environments in certain files which made keeping on top if which working directory was in tough.... however this has now been solved and tested by returning to the previous folder (same as project directory) with ".." before each file path.
